import { useState } from "react";
import { Auth } from "@aws-amplify/auth";
import { API } from "@aws-amplify/api";
import { withSSRContext } from "aws-amplify";
// import { v4 as uuidv4 } from "uuid";

// queries and mutuations are autogenerated once you write the schema
import { createUser, updateUser } from "../src/graphql/mutations";
import { getUser } from "../src/graphql/queries";
import NavBar from "../components/NavBar";

// renders before component renders on browsers on the server-side - safely checks authentication
export async function getServerSideProps({ req, res }) {
  const { Auth, API } = withSSRContext({ req });

  try {
    const user = await Auth.currentAuthenticatedUser();
    const response = await API.graphql({
      query: getUser,
      variables: { id: user.attributes.sub },
    });

    if (response.data.getUser) {
      return {
        props: {
          mode: "EDIT",
          user: response.data.getUser,
          error: false,
        },
      };
    } else {
      return {
        props: {
          mode: "ADD",
          error: false,
        },
      };
    }
  } catch (error) {
    console.log(error, "SERVER SIDE PROPS ERROR PRINTED");
  }

  return {
    props: {
      error: true,
    },
  };
}

const EditUser = ({ error, mode, user }) => {
  // naming convention must match GraphQL schema if mode is edit then submit
  const [firstName, setFirstName] = useState(
    mode === "EDIT" ? user.firstName : ""
  );
  const [lastName, setLastName] = useState(
    mode === "EDIT" ? user.lastName : ""
  );
  const [description, setDescription] = useState(
    mode === "EDIT" ? user.description : ""
  );

  const handleEditUserSubmission = async (event) => {
    const currentUser = await Auth.currentAuthenticatedUser();
    // const id = currentAuthenticatedUser.attributes.sub;
    // console.log(currentUser, "PRINT CURRENT USER");
    // console.log(id, "PRINT CURRENT USER ID");
    event.preventDefault();
    try {
      const addUser = await API.graphql({
        // queries and mutuations are autogenerated once you write the schema
        // If query mode is edit then update user otherwise create new user
        query: mode === "EDIT" ? updateUser : createUser,
        variables: {
          input: {
            id: currentUser.attributes.sub,
            // id: uuidv4(),
            firstName,
            lastName,
            description,
          },
        },
      });
      console.log(addUser, "SUCCESS: edit user data submitted");
      // window.location.heref = "/";
    } catch (error) {
      console.log(error, "FAIL: edit user fail submission");
    }
  };

  return (
    <div className='d-flex flex-column justify-content-center w-100 h-100'>
      <NavBar />
      <h4 className='align-self-center'>
        Please use this form to edit user details
      </h4>
      <form
        className='w-50 align-self-center'
        onSubmit={handleEditUserSubmission}
      >
        <p className='mt-2'> First Name</p>
        <input
          type='text'
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
        />
        <p className='mt-2'>Family Name</p>
        <input
          type='text'
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
        />
        <p className='mt-2'>Short Description</p>
        <textarea
          type='textarea'
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <br />
        <button className='mt-3 btn btn-primary' type='submit'>
          Update
        </button>
      </form>
    </div>
  );
};
export default EditUser;
