import NavBar from "../components/NavBar";
import { useState } from "react";
import { Auth } from "@aws-amplify/auth";
import { API } from "@aws-amplify/api";

// queries and mutuations are autogenerated once you write the schema
import { createUser, updateUser } from "../src/graphql/mutations";

const EditUser = () => {
  // naming convention must match GraphQL schema
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [description, setDescription] = useState("");

  const handleEditUserSubmission = async (event) => {
    const currentUser = await Auth.currentAuthenticatedUser();
    // const id = currentAuthenticatedUser.attributes.sub;
    console.log(currentUser, "PRINT CURRENT USER");
    // console.log(id, "PRINT CURRENT USER ID");
    event.preventDefault();
    try {
      const addUser = await API.graphql({
        // queries and mutuations are autogenerated once you write the schema
        query: createUser,
        variables: {
          input: {
            id: currentUser.attributes.sub,
            firstName,
            lastName,
            description,
          },
        },
      });
      console.log(addUser, "SUCCESS: edit user data submitted");
    } catch (error) {
      console.log(error, "FAIL: edit user fail submission");
    }
  };

  return (
    <div className='d-flex flex-column justify-content-center w-100 h-100'>
      <NavBar />
      <h4 className='align-self-center'>
        Please use this form to edit user details
      </h4>
      <form
        className='w-50 align-self-center'
        onSubmit={handleEditUserSubmission}
      >
        <p className='mt-2'> First Name</p>
        <input
          type='text'
          value={firstName}
          onChange={(e) => setFirstName(e.target.value)}
        />
        <p className='mt-2'>Family Name</p>
        <input
          type='text'
          value={lastName}
          onChange={(e) => setLastName(e.target.value)}
        />
        <p className='mt-2'>Short Description</p>
        <textarea
          type='textarea'
          value={description}
          onChange={(e) => setDescription(e.target.value)}
        />
        <br />
        <button className='mt-3 btn btn-primary' type='submit'>
          Update
        </button>
      </form>
    </div>
  );
};

export default EditUser;
